name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and test with Docker compose
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
